---

- name: User management
  hosts: all
  become: true

  tasks:
  - name: creating User
    user:
      name: "{{ item }}"
      shell: /bin/bash
      state: absent
      remove: yes  
    loop:
       - bhuvan
       - megha
       - hari

